### ISSUE TITLE
401 Error - API Key Invalid","status":401,"detail":"Your API key may be invalid, or you've attempted to access the wrong datacenter."

### ISSUE THREAD

**Issue by j-milner-wlc** [up-n-running/ZenChimp-Zendesk-App-Mailchimp-Sync#2]
I received the following error message:

401 - error -

{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"API Key Invalid","status":401,"detail":"Your API key may be invalid, or you've attempted to access the wrong datacenter.","instance":"f9c0b75b-8e09-4b80-9c4e-5d0054fce3cc"}

**Comment by up-n-running** [comment]
This happens when your mailchimp api credentials are incorrect.

Please log in to mailchimp.

Then in a seperate tab open zendesk and goto
admin -> Manage -> Zendhimp Mailchimp Sync

And double check the following three settings:

- Mailchimp API Key
- Mailchimp Datacentre Prefix
- Mailchimp List ID of List to sync to

Then retry :)
